version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  monet:
    build: ./
    container_name: queue_server
    links:
      - redis
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env
